name: deloitte
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  http: ^1.1.0
  file_picker: ^8.0.0+1
  path_provider: ^2.1.3
  path: ^1.8.3
  shared_preferences: ^2.2.3
  embeddedsdk: ^0.3.1
  webview_flutter: ^4.5.0
  webview_flutter_web: ^0.2.2+4
  webview_flutter_platform_interface: ^2.10.0
  pointer_interceptor: ^0.10.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/DELBlack.jpg
    - assets/images/DELWhite.jpg
    - assets/images/deloitte.jpg
    - assets/images/upload.png
    - assets/images/upload_f.jpg
    - assets/images/uplooo.png
    - assets/images/login.png
    - assets/images/del.png
    - assets/images/R.png
    - assets/images/verification.png
    - assets/icons/view.svg
    - assets/icons/home.svg
    - assets/icons/statistics.svg
    - assets/icons/settings.svg
    - assets/icons/contact.svg
    - assets/icons/globe.svg
